# Generated by Django 3.0.6 on 2020-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
