# Generated by Django 3.0.6 on 2020-05-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_feature_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='features', to='dashboard.Feature'),
        ),
        migrations.AddField(
            model_name='project',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='project_milestones', to='dashboard.Milestone'),
        ),
    ]
