# Generated by Django 3.0.6 on 2020-05-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200524_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='milestones',
            new_name='features',
        ),
    ]
